name: ci
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: [18.x, 20.x]   # â† quitamos 22.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Backend - install, lint, build, test
        working-directory: backend
        run: |
          npm ci
          npm run lint --if-present
          npm run build
          npm test

      - name: Frontend - install, lint, build
        working-directory: frontend
        run: |
          npm ci
          npm run lint --if-present
          npm run build
